services:
  db:
    image: postgres:15
    container_name: postgres_dw
    networks:
      - lighthouse_net
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INGEST_USER=${INGEST_USER}
      - INGEST_PASSWORD=${INGEST_PASSWORD}
      - DBT_USER=${DBT_USER}
      - DBT_PASSWORD=${DBT_PASSWORD}
      - DASH_USER=${DASH_USER}
      - DASH_PASSWORD=${DASH_PASSWORD}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_lighthouse
    networks:
      - lighthouse_net
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

networks:
  lighthouse_net:
    driver: bridge